version: 1
repository:
    url: https://github.com/go-git/go-git.git
    tag: latest
    auth:
        token: my-token
        username: my-username
        password: my-password
        sshKey: my-ssh-key
parameters:
    - name: name1
      description: Description 1
      type: bool
      default: default 1
      value: value 1
    - name: name 2
      description: Description 2
      type: bool
      default: default 2
      value: value 2
    - name: name 3
      description: Description 3
      type: bool
      default: default 3
      value: value 3            